Use `TiffPage` properties in TiffFile v3 plugin
imageio/imageio pull request #1031
Opened 2023-08-19 12:30 UTC by lschr

According to comments in the source, this was previously not possible due to supporting Python 3.7, which is now EOLed.

Fixes #970 (`properties()` fails for TIFF files without resolution tags).

2023-08-21 10:29 UTC, lschr commented
I guess Python 3.7 needs to be removed from the CI, too.

2023-08-27 19:14 UTC, FirefoxMetzger requested changes
Thanks for another PR @Ischr. Looking pretty good so far :)

Could you merge with or rebase on master, so that your deprecation of python 3.7 takes effect here and we can see the full CI log?

2023-08-28 09:38 UTC, lschr commented on imageio/plugins/tifffile_v3.py
> -            )
I have no serious opinion about this issue, just some thoughts:

- If there is a warning about denominator being 0, should there also be one for the numerator being 0 (or less)? A resolution of 0 or less pixels per `ResolutionUnit` is nonsensical. Should there be warnings for other tags, too, that can have obviously undefined values (e.g., `ResolutionUnit`)?
- Doesn't a default value of 1 (probably in connection with missing/invalid `ResolutionUnit`; which software would provide invalid `X/YResolution`, but valid `ResolutionUnit`?) adequately suggest that there is no information about the resolution?

And related to this: If an invalid resolution is detected, should `ImageProperties.spacing` be set to `None`?

2023-08-29 11:22 UTC, lschr commented
#1035 should fix the failing readthedocs check.

2023-08-29 18:48 UTC, FirefoxMetzger commented
> https://github.com/imageio/imageio/pull/1035 should fix the failing readthedocs check.

Reviewed and merged :)

2023-08-30 01:13 UTC, lschr commented
To restore the warning saw no way around reintroducing the `_get_resolution` function.

I added tests to check for missing `ResolutionUnit` and `XResolution` tags.

2023-09-02 11:30 UTC, FirefoxMetzger approved these changes

2023-09-02 11:31 UTC, FirefoxMetzger commented
Nice work @lschr 

LGTM 🚀

2023-09-02 11:35 UTC, merged