Support HEIF image file
imageio/imageio pull request #1042
Opened 2023-09-30 12:45 UTC by Pandede

Resolves #1021.
The previous pull request #1040 is closed as the redundant commits.
And also, move `pillow-heif` to be a plugin rather than extra requirement of `Pillow` (thanks for the advice of @bigcat88).

2023-09-30 12:48 UTC, bigcat88 commented on setup.py
> +    "heif": ["pillow-heif"],
should be:
```
"pillow-heif": [],
```

2023-09-30 13:17 UTC, bigcat88 commented
never mind about my previous deleted comment.

as I see, CI needs wheels for PyPy3.8 - if I will know that this will have high chances to be merged, I can restore the publishing of PyPy3.8 wheels for the next release, if it is needed.

2023-10-14 15:08 UTC, FirefoxMetzger requested changes
Awesome initiative, thanks @Pandede 🚀 This looks pretty good from the plugin implementation side. I think we'll only need one round of reviews before we can merge.

I think we should also properly register the format so that pillow is automatically tried first for `.heic` files. To do so we need to add a new [`FileExtension`](https://github.com/imageio/imageio/blob/0bbf1962c7c36ebee28639aee8441e01d4168215/imageio/config/extensions.py#L9) in the relevant [config file](https://github.com/imageio/imageio/blob/0bbf1962c7c36ebee28639aee8441e01d4168215/imageio/config/extensions.py#L1854-L1857). This will also add the necessary documentation so that HEIC shows up in the list of supported formats :)

Beyond that, there is one change (making `pillow_heif` option) that I would like to see before we merge.

2023-10-15 19:55 UTC, bigcat88 commented
> as I see, CI needs wheels for PyPy3.8 - if I will know that this will have high chances to be merged, I can restore the publishing of PyPy3.8 wheels for the next release, if it is needed.

done from my side, new release was published :)

2023-10-16 05:23 UTC, Pandede commented on tests/test_pillow.py
> +    url = "https://nokiatech.github.io/heif/content/images/surfer_1440x960.heic"
I may use the HEIC images in this repository instead: https://github.com/tigranbs/test-heic-images.

2023-10-16 05:54 UTC, Pandede commented
The tests are failed as the latest upgrade of `Pillow`. All tests passed if `Pillow==10.0.1` but failed if `Pillow==10.1.0`.

2023-10-18 04:50 UTC, FirefoxMetzger commented
Yes. There is another issue related to pillow's recent upgrade. I'll pin pillow for now and then see how we can best resolve this.

2023-10-31 14:49 UTC, FirefoxMetzger approved these changes
Looks good from my side.

I will check why why the pypi CI no longer likes the av package and then we should be able to get a green CI :)

2023-10-31 20:30 UTC, merged

2023-11-08 14:57 UTC, FirefoxMetzger commented on imageio/config/extensions.py
> +        name="High Efficiency Image File Format", extension=".heic", priority=["pillow"]
@kmilos Looks like @Pandede is one step ahead: https://github.com/imageio/imageio/pull/1048

AVIF support is already merged :) as for HIF I'm not sure. Is it just a different suffix for HEIF but actually the same format?

2023-11-08 15:17 UTC, kmilos commented on imageio/config/extensions.py
> +        name="High Efficiency Image File Format", extension=".heic", priority=["pillow"]
Yes. Some cameras now output .HIF directly (I guess limitations of sdcard  filesystem like old 8.3 filename format from DOS times!)

2023-11-23 11:22 UTC, kmilos commented on imageio/config/extensions.py
> +        name="High Efficiency Image File Format", extension=".heic", priority=["pillow"]
2.33.0 is still missing ".heif" and ".hif".

Also, libheif from 1.17 supports the JPEG 2000 codec inside the HEIF container w/ a ".hej2" extension, see https://www.itu.int/rec/T-REC-T.815/en

2023-11-28 03:18 UTC, Pandede commented on imageio/config/extensions.py
> +        name="High Efficiency Image File Format", extension=".heic", priority=["pillow"]
Maybe create a new issue about the multiple extensions of HEIF?