Support using offline test image cache w/ `-m "not needs_internet"`
imageio/imageio pull request #1081
Opened 2024-05-04 11:55 UTC by mgorny

Disable fetching/updating `.test_images` cache when `-m "not needs_internet"` is requested.  Instead, either reuse the existing cache if one is available, or skip the relevant tests.

This preserves the current behavior for the two scenarios: when `-m "not needs_internet"` is not passed, the cache is normally cloned and updated.  If it is passed and cache does not exist, the tests are skipped as before.  However, if one populates the cache first (either via running the tests or manually cloning it) and then passes `-m "not needs_internet"`, the tests run against the existing cache.

Fixes #1078

2024-05-10 20:41 UTC, FirefoxMetzger requested changes
Pretty much good to go - thanks for the PR 🚀

I only have one nitpick ... I also merged a fix for the failing tests earlier - now the tests run correctly again. If they are happy and we add the `.` then I am happy, too :)

2024-05-10 20:41 UTC, FirefoxMetzger commented on tests/conftest.py
> +            pytest.skip("Internet use disabled and `.test_images` not found")
```suggestion
            pytest.skip("Internet use disabled and `.test_images` not found.")
```

Nit - but I like sentences ending with a period.

2024-05-11 04:25 UTC, mgorny commented
Done. Do you want me to rebase and squash the change?

2024-05-11 06:19 UTC, FirefoxMetzger commented
No that's fine. I will squash-merge :)

2024-05-11 06:24 UTC, FirefoxMetzger approved these changes
LGTM once tests are happy. 

GHA has a flaky pypy runner right now. One of the tests sporadically fails while setting up, so it is unrelated to this PR.

2024-05-11 06:28 UTC, merged

2024-05-11 07:01 UTC, mgorny commented
Thanks!

For the record, I don't think you need to test against pypy-3.8 anymore. Upstream is no longer maintaining that branch, and new releases include 2.7, 3.9 and 3.10 only.

2024-05-11 07:17 UTC, FirefoxMetzger commented
> For the record, I don't think you need to test against pypy-3.8 anymore. Upstream is no longer maintaining that branch, and new releases include 2.7, 3.9 and 3.10 only.

Thanks for the heads up :) I have also noticed this when adding tests for `pypy-3.10` recently. I was thinking of dropping tests for it alongside the CPython 3.8 deprecation this October.