SPE plugin: Support new SDT-control metadata
imageio/imageio pull request #989
Opened 2023-05-08 09:42 UTC by lschr

A new version of SDT-control was released, bumping the metadata field version to 5.01. This refactors the SDT-control metadata parsing code to read v5.00 and v5.01 as well as to make it easier to adapt to future changes.

2023-05-16 06:05 UTC, FirefoxMetzger requested changes
Nice work @Ischr as always 🚀 

I only have a few comments related to the handling of incorrect/corrupt SPE, where we may want to become more chatty about things failing so that users get informed and can start investigating why they are using corrupt files.

2023-05-23 09:42 UTC, lschr commented on imageio/plugins/spe.py
> +            logger.debug("SDT-control comments not found.")
`comver == (-1, -1)` is, if not by accident, true for SPE files that were generated by software other than SDT-control, so I think debug is the right logging level.

2023-05-23 09:47 UTC, lschr commented on imageio/plugins/spe.py
> +                    logger.debug(
True. Should we use `logger.warn` or `warnings.warn`? So far `logger` is used throughout the file, but this has the downside of not being easy to turn off if desired (i.e., no `warnings.catch_warnings()`) and thus messing up, for instance Jupyter notebooks when loading hundreds of files.

2023-05-23 09:49 UTC, lschr commented on imageio/plugins/spe.py
> +                continue
I think that a warning will be sufficient. Image data as well as non-SDT-control metadata is still read.

Should we use `logger.warn` or `warnings.warn`? So far `logger` is used throughout the file, but this has the downside of not being easy to turn off if desired (i.e., no `warnings.catch_warnings()`) and thus messing up, for instance Jupyter notebooks when loading hundreds of files.

2023-05-23 19:14 UTC, FirefoxMetzger commented on imageio/plugins/spe.py
> +                continue
I have a preference towards `warnings.warn` (exactly for the reason you mentioned), but I will accept either choice you make here :)

2023-05-23 19:15 UTC, FirefoxMetzger commented on imageio/plugins/spe.py
> +                    logger.debug(
The same as you choose in the previous point with a preference for `warnings.warn`.

2023-05-23 19:17 UTC, FirefoxMetzger commented on imageio/plugins/spe.py
> +            logger.debug("SDT-control comments not found.")
Works for me. Thanks for clarifying :)

2023-05-25 03:39 UTC, FirefoxMetzger approved these changes

2023-05-25 03:39 UTC, merged

2023-05-25 03:40 UTC, FirefoxMetzger commented
Thanks again @lschr for making ImageIO more awesome! 🚀